create table public.staff (
  staff_id bigint generated by default as identity not null,
  staff_name character varying not null,
  "staff_phoneNo" character varying not null,
  access_level bigint not null default '1'::bigint,
  joined_at timestamp with time zone not null default now(),
  staff_email character varying not null,
  uuid uuid not null,
  status character varying not null,
  constraint staff_pkey primary key (staff_id),
  constraint staff_staff_id_key unique (staff_id),
  constraint staff_uuid_fkey foreign KEY (uuid) references auth.users (id) on update CASCADE on delete RESTRICT
) TABLESPACE pg_default;

create table public.movie (
  movie_id bigint generated by default as identity not null,
  movie_name character varying not null,
  movie_desc character varying not null,
  year bigint not null,
  age_rating character varying not null,
  duration bigint not null,
  genre text[] not null,
  created_at timestamp with time zone not null default now(),
  added_by bigint not null,
  image_url text null,
  constraint movie_pkey primary key (movie_id),
  constraint movie_movie_id_key unique (movie_id),
  constraint movie_added_by_fkey foreign KEY (added_by) references staff (staff_id) on update CASCADE on delete RESTRICT
) TABLESPACE pg_default;

create table public.customer (
  cust_id bigint generated by default as identity not null,
  cust_name character varying not null,
  email character varying not null,
  phone_no character varying not null,
  uuid uuid not null,
  constraint customer_pkey primary key (cust_id),
  constraint customer_uuid_fkey foreign KEY (uuid) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.fnb (
  fnb_id bigint generated by default as identity not null,
  fnb_name character varying not null,
  fnb_desc character varying not null,
  type character varying not null,
  created_at timestamp with time zone not null default now(),
  price double precision not null,
  image_url text null,
  constraint fnb_pkey primary key (fnb_id),
  constraint fnb_fnb_id_key unique (fnb_id)
) TABLESPACE pg_default;

create table public.order (
  order_id bigint generated by default as identity not null,
  order_date date not null default now(),
  order_time time with time zone not null default now(),
  payment_method character varying not null,
  status character varying not null,
  cust_id bigint null,
  staff_id bigint null,
  card_reference_number bigint null,
  constraint order_pkey primary key (order_id),
  constraint order_order_id_key unique (order_id),
  constraint order_cust_id_fkey foreign KEY (cust_id) references customer (cust_id),
  constraint order_staff_id_fkey foreign KEY (staff_id) references staff (staff_id)
) TABLESPACE pg_default;

create table public.order_list (
  order_list_id bigint generated by default as identity not null,
  fnb_id bigint null,
  order_id bigint not null,
  quantity bigint not null,
  price double precision not null,
  constraint order_list_pkey primary key (order_list_id),
  constraint order_list_order_list_id_key unique (order_list_id),
  constraint order_list_fnb_id_fkey foreign KEY (fnb_id) references fnb (fnb_id) on update CASCADE on delete RESTRICT,
  constraint order_list_order_id_fkey foreign KEY (order_id) references "order" (order_id) on update CASCADE on delete RESTRICT
) TABLESPACE pg_default;

create table public.customer_device (
  id uuid not null default gen_random_uuid (),
  cust_id bigint not null,
  fcm_token text not null,
  created_at timestamp with time zone not null default now(),
  constraint customer_device_pkey primary key (id),
  constraint customer_device_cust_id_fkey foreign KEY (cust_id) references customer (cust_id) on update CASCADE on delete RESTRICT
) TABLESPACE pg_default;

create table public.complaint (
  complaint_id bigint generated by default as identity not null,
  title character varying not null,
  complaint_type character varying not null,
  "desc" character varying not null,
  date date not null,
  cust_id bigint not null,
  reply character varying null,
  status character varying not null,
  constraint complaint_pkey primary key (complaint_id),
  constraint complaint_cust_id_fkey foreign KEY (cust_id) references customer (cust_id) on update CASCADE on delete RESTRICT
) TABLESPACE pg_default;

create table public.cinema_hall (
  hall_id bigint generated by default as identity not null,
  hall_type character varying not null,
  constraint cinema hall_pkey primary key (hall_id)
) TABLESPACE pg_default;

create table public.seat (
  seat_no character varying not null,
  hall_id bigint not null,
  seat_type character varying not null,
  constraint seat_pkey primary key (seat_no, hall_id),
  constraint seat_hall_id_fkey foreign KEY (hall_id) references cinema_hall (hall_id) on update CASCADE on delete RESTRICT
) TABLESPACE pg_default;

create table public.showtimes (
  showtime_id bigint generated by default as identity not null,
  movie_id bigint not null,
  date date not null,
  time time with time zone not null,
  hall_id bigint not null,
  status character varying not null,
  created_at timestamp with time zone not null default now(),
  adult_price double precision not null,
  senior_price double precision not null,
  child_price double precision not null,
  constraint showtimes_pkey primary key (showtime_id),
  constraint showtimes_showtime_id_key unique (showtime_id),
  constraint showtimes_hall_id_fkey foreign KEY (hall_id) references cinema_hall (hall_id) on update CASCADE on delete RESTRICT,
  constraint showtimes_movie_id_fkey foreign KEY (movie_id) references movie (movie_id) on update CASCADE on delete RESTRICT
) TABLESPACE pg_default;

create table public.ticket (
  ticket_id bigint generated by default as identity not null,
  showtime_id bigint not null,
  cust_id bigint null,
  total_price double precision not null,
  purchased_at timestamp with time zone null default (now() AT TIME ZONE 'utc'::text),
  constraint ticket_pkey primary key (ticket_id),
  constraint ticket_ticket_id_key unique (ticket_id),
  constraint ticket_cust_id_fkey foreign KEY (cust_id) references customer (cust_id) on update CASCADE on delete RESTRICT,
  constraint ticket_showtime_id_fkey foreign KEY (showtime_id) references showtimes (showtime_id) on update CASCADE on delete RESTRICT
) TABLESPACE pg_default;

create table public.seat_taken (
  seat_taken_id bigint generated by default as identity not null,
  seat_no character varying not null,
  ticket_id bigint not null,
  date date not null,
  status character varying not null,
  hall_id bigint null,
  constraint seat_taken_pkey primary key (seat_taken_id),
  constraint fk_seat_taken_seat foreign KEY (seat_no, hall_id) references seat (seat_no, hall_id),
  constraint seat_taken_ticket_id_fkey foreign KEY (ticket_id) references ticket (ticket_id) on update CASCADE on delete RESTRICT
) TABLESPACE pg_default;

create table public.feedback (
  feedback_id bigint generated by default as identity not null,
  ticket_id bigint null,
  rating bigint null,
  "desc" character varying null,
  date date not null,
  constraint feedback_pkey primary key (feedback_id),
  constraint feedback_feedback_id_key unique (feedback_id),
  constraint feedback_ticket_id_fkey foreign KEY (ticket_id) references ticket (ticket_id) on update CASCADE on delete RESTRICT
) TABLESPACE pg_default;

create table public.group_booking (
  group_id bigint generated by default as identity not null,
  access_code bigint not null,
  owner_cust_id bigint not null,
  showtime_id bigint not null,
  status character varying not null,
  created_at timestamp with time zone not null default now(),
  constraint group_booking_pkey primary key (group_id),
  constraint group_booking_access_code_key unique (access_code),
  constraint group_booking_owner_cust_id_fkey foreign KEY (owner_cust_id) references customer (cust_id) on update CASCADE on delete RESTRICT,
  constraint group_booking_showtime_id_fkey foreign KEY (showtime_id) references showtimes (showtime_id) on update CASCADE on delete RESTRICT
) TABLESPACE pg_default;